export const Columns = [
    {
        Header:"id",
        accessor:"id"
    },
    {
        Header:"Name",
        accessor:"name"
    },
    {
        Header:"E-mail",
        accessor:"email"
    },
    {
        Header:"Date",
        accessor:"date"
    },
    {
        Header:"Time",
        accessor:"time"
    },
    {
        Header:"Professionals",
        accessor:"professionals"
        
    },
    {
        Header:"Category",
        accessor:"category"
    },
    {
        Header:"Message",
        accessor:"message"
    },{
        Header:"Gmeet-link",
        accessor:"gmeet-link"
    }

]