export const data = [
    {
        id:1,
        name:"Karthi",
        email:"test@gmail.com",
        date:"30-01-2020",
        professioanl:"sam",
        category:"despressed"
    },
    {
        id:2,
        name:"Karthi",
        email:"test@gmail.com",
        date:"30-01-2020",
        professioanl:"sam",
        category:"despressed"
    },
    {
        id:3,
        name:"Karthi",
        email:"test@gmail.com",
        date:"30-01-2020",
        professioanl:"sam",
        category:"despressed"
    },
    {
        id:4,
        name:"Karthi",
        email:"test@gmail.com",
        date:"30-01-2020",
        professioanl:"sam",
        category:"despressed"
    }
]